### ISSUE TITLE
Error: uninitialized constant #<Class:SpeedtestNet::Download>::Timeout (NameError)

### ISSUE THREAD

**Issue by akashgp09** [ryonkn/speedtest_net#49]
The following code provided in README is throwing error on execution.

```ruby
require 'speedtest_net'
result = SpeedtestNet.run                 
result.server                                
result.client                             
result.latency  
result.download                         
result.upload                                
result.pretty_latency                        
result.pretty_download                
result.pretty_upload   
```

#### Output

```bash
Traceback (most recent call last):
        2: from /home/akashgp09/apps/ruby-internet-speed/foo/main.rb:3:in `<main>'
        1: from /var/lib/gems/2.7.0/gems/speedtest_net-0.8.1/lib/speedtest_net.rb:15:in `run'
/var/lib/gems/2.7.0/gems/speedtest_net-0.8.1/lib/speedtest_net/download.rb:30:in `measure': uninitialized constant #<Class:SpeedtestNet::Download>::Timeout (NameError)
        3: from /home/akashgp09/apps/ruby-internet-speed/foo/main.rb:3:in `<main>'
        2: from /var/lib/gems/2.7.0/gems/speedtest_net-0.8.1/lib/speedtest_net.rb:15:in `run'
        1: from /var/lib/gems/2.7.0/gems/speedtest_net-0.8.1/lib/speedtest_net/download.rb:29:in `measure'
/var/lib/gems/2.7.0/gems/speedtest_net-0.8.1/lib/speedtest_net/download.rb:36:in `rescue in measure': uninitialized constant #<Class:SpeedtestNet::Download>::Timeout (NameError)
```

#### Environment:
- Linux (ubuntu 20.04)
- Ruby V 2.7

**Comment by ryonkn** [comment]
@akashgp09 san
Thank you for reporting this issue, it has been fixed in the #50 pull request.

[speedtest_net](https://rubygems.org/gems/speedtest_net/versions/0.9.0) gem has also been released as v0.9.0.
