### ISSUE TITLE
Error: Failed to url-encode content `(null)' (Curl::Err::InvalidPostFieldError)

### ISSUE THREAD

**Issue by ryonkn** [ryonkn/speedtest_net#52]
Failed to url-encode content `(null)' (Curl::Err::InvalidPostFieldError) error in SpeedtestNet::Upload.multi_uploader

### Run
```ruby
require 'speedtest_net'
result = SpeedtestNet.run
```
### Output
```ruby
/Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:56:in `to_str': Failed to url-encode content `(null)' (Curl::Err::InvalidPostFieldError)
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:56:in `join'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:56:in `http_post'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:56:in `block in multi_uploader'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:53:in `each'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:53:in `multi_uploader'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:32:in `block (2 levels) in measure'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:30:in `each'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:30:in `block in measure'
	from /Users/ryonkn/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /Users/ryonkn/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
	from /Users/ryonkn/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
	from /Users/ryonkn/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
	from /Users/ryonkn/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net/upload.rb:29:in `measure'
	from /Users/ryonkn/ghq/github.com/ryonkn/speedtest_net/lib/speedtest_net.rb:16:in `run'
	from (irb):3:in `<main>'
	... 1 levels...
```

### Environment
- MacBook Pro (13-inch, M1, 2020)
- macOS Monterey
- ruby 3.0.2p10

**Comment by ryonkn** [comment]
https://github.com/ryonkn/speedtest_net/blob/32aaf5f5f94d46209f34a7ec192c0fd1c2b25dc1/lib/speedtest_net/upload.rb#L56

## Success if content size is less than 23,999,999
```ruby
irb(main):015:0> Curl::PostField.content('content1', 'A' * 23_999_999).to_str.size
=> 24000008
```

## Failed if content size is greater than 24,000,000
```ruby
irb(main):016:0> Curl::PostField.content('content1', 'A' * 24_000_000).to_str.size
(irb):16:in `to_str': Failed to url-encode content `(null)' (Curl::Err::InvalidPostFieldError)
	from (irb):16:in `<main>'
	from bin/console:15:in `<main>'
```
